complexity:
  LongMethod:
    threshold: 100
    ignoreAnnotated: ['Composable']
  LongParameterList:
    functionThreshold: 10
    constructorThreshold: 10
    ignoreDefaultParameters: true

style:
  MaxLineLength:
    maxLineLength: 120
    excludeCommentStatements: true
